package test

import (
	"fmt"
	"path/filepath"
	"testing"
)

// TestExtend pins ordered hooks, fail-open handling, commands and package precedence.
func TestExtend(t *testing.T) {
	t.Run("task hooks run in name order, each changing the task the next one sees", func(t *testing.T) {
		s := fresh(t)
		s.hook("a-route", []string{"task"}, `echo '{"task":{"model":"fake:big","prompt":"fix it (routed)"}}'`)
		s.hook("b-context", []string{"task"}, `echo '{"task":{"prompt":"Context first. fix it (routed)"}}'`)
		r := s.ask("-m", "fake:small", "-w", "fix it")
		eq(t, r.code, 0)
		eq(t, s.calls()[0].s("model"), "big")
		eq(t, s.calls()[0].s("stdin"), "Context first. fix it (routed)")
		input := s.hookCalls()[1]["input"].(map[string]any)
		task := input["task"].(map[string]any)
		eq(t, task["prompt"], "fix it (routed)")
	})
	t.Run("a task hook can refuse a task, which then never runs", func(t *testing.T) {
		s := fresh(t)
		s.hook("guard", []string{"task"}, `case "$input" in *'"write":true'*) echo '{"refuse":"no writes here"}';; esac`)
		r := s.ask("-m", "fake:small", "-w", "delete everything")
		eq(t, r.code, 1)
		eq(t, len(s.calls()), 0)
		match(t, r.stderr, `(?m) · failed · .* · refused by hook guard: no writes here$`)
	})
	t.Run("a hook that crashes or prints nonsense changes nothing and leaves a note", func(t *testing.T) {
		s := fresh(t)
		s.hook("broken", []string{"task"}, "echo 'Error: boom' >&2; echo 'runtime banner' >&2; exit 1")
		s.hook("chatty", []string{"task"}, "echo 'not json'")
		s.hook("typo", []string{"task"}, `echo '{"task":{"write":"yes","dir":"/"}}'`)
		r := s.ask("-m", "fake:small", "look")
		eq(t, r.code, 0)
		eq(t, s.calls()[0].s("access"), "read")
		match(t, r.stderr, `(?m)^ask \w{6} · hook broken · failed: .*boom`)
		match(t, r.stderr, `(?m)^ask \w{6} · hook chatty · failed: printed something other than JSON$`)
		match(t, r.stderr, `(?m)^ask \w{6} · hook typo · ignored a change to "write"$`)
		match(t, r.stderr, `(?m)^ask \w{6} · hook typo · ignored a change to "dir"$`)
	})
	t.Run("a result hook can ask the same agent for a follow-up, and the rounds make one result", func(t *testing.T) {
		s := fresh(t)
		s.hook("verify", []string{"result"}, `case "$input" in *'"answer":"fake: try again"'*) ;; *) echo '{"followup":"try again","note":"tests fail"}';; esac`)
		r := s.run([]string{"batch", "-m", "fake:small", "-"}, `[{"prompt":"fix the bug"}]`, nil)
		result := objects(t, r.stdout)[0]
		first, second := s.calls()[0], s.calls()[1]
		eq(t, second.s("session"), fmt.Sprintf("s-%.0f", first.n("pid")))
		eq(t, second.s("stdin"), "try again")
		eq(t, result.s("answer"), "fake: try again")
		eq(t, result.n("followups"), 1.0)
		jsonEqual(t, result["usage"], object{"input": 20, "output": 10, "cached": 4, "cost": 0.02})
		match(t, r.stderr, `(?m)^ask \w{6} · hook verify · tests fail$`)
		match(t, r.stderr, `(?m)^ask \w{6} · hook verify · follow-up: try again$`)
	})
	t.Run("follow-ups stop after three, so a hook that is never satisfied cannot loop forever", func(t *testing.T) {
		s := fresh(t)
		s.hook("never", []string{"result"}, `echo '{"followup":"again"}'`)
		r := s.ask("-m", "fake:small", "go")
		eq(t, len(s.calls()), 4)
		match(t, r.stderr, `hook never · asked for a follow-up after 3; stopping`)
	})
	t.Run("a result hook can fail a result", func(t *testing.T) {
		s := fresh(t)
		s.hook("strict", []string{"result"}, `echo '{"fail":"no tests were run"}'`)
		r := s.ask("-m", "fake:small", "go")
		eq(t, r.code, 1)
		eq(t, r.stdout, "")
		match(t, r.stderr, `(?m) · failed · .* · failed by hook strict: no tests were run$`)
	})
	t.Run("a hook gets only the events it declares, and --no-hooks skips them all", func(t *testing.T) {
		s := fresh(t)
		s.hook("after", []string{"result"}, ":")
		s.ask("-m", "fake:small", "go")
		eq(t, stringsField(s.hookCalls(), "event"), []string{"result"})
		match(t, s.hookCalls()[0].s("run"), `^\w{6}$`)
		s.ask("-m", "fake:small", "--no-hooks", "go")
		eq(t, len(s.hookCalls()), 1)
	})
	t.Run("a command runs as ask NAME with its arguments and exit code, and can run ask itself", func(t *testing.T) {
		s := fresh(t)
		s.script("commands", "twice", "# ask-command: ask the same question twice\n\"$ASK_BIN\" -m fake:small \"$@\" 2>/dev/null\n\"$ASK_BIN\" -m fake:small \"$@\" 2>/dev/null\nexit 3")
		r := s.ask("twice", "hello")
		eq(t, r.code, 3)
		eq(t, r.stdout, "fake: hello\nfake: hello\n")
		match(t, s.ask("--help").stdout, `your commands\n {2}ask twice {2}ask the same question twice`)
	})
	t.Run("ask's own commands win over yours of the same name", func(t *testing.T) {
		s := fresh(t)
		s.script("commands", "models", "echo mine")
		match(t, s.ask("models").stdout, `(?m)^fake:small$`)
	})
	t.Run("a package from git adds agents, hooks and commands; yours win; install alone updates it", func(t *testing.T) {
		s := fresh(t)
		repo := filepath.Join(s.tmp, "src", "team", "tools")
		s.mkdir(repo)
		git := s.gitAt(repo)
		git("init", "-q", "-b", "main")
		s.scriptAt(repo, "agents", "fake", "echo 'package agent'")
		s.scriptAt(repo, "commands", "hello", "echo 'hello v1'")
		git("add", ".")
		git("-c", "user.email=t@t", "-c", "user.name=t", "commit", "-qm", "v1")
		installed := s.ask("install", repo)
		match(t, installed.stderr, `installed local/team/tools: agents: fake · commands: hello`)
		eq(t, s.ask("hello").stdout, "hello v1\n")
		eq(t, s.ask("-m", "fake:small", "hi").stdout, "fake: hi\n")
		match(t, s.ask("packages").stdout, `(?m)^local/team/tools\tagents: fake · commands: hello$`)
		s.scriptAt(repo, "commands", "hello", "echo 'hello v2'")
		git("-c", "user.email=t@t", "-c", "user.name=t", "commit", "-qam", "v2")
		match(t, s.ask("install").stderr, `local/team/tools: updated`)
		eq(t, s.ask("hello").stdout, "hello v2\n")
		match(t, s.ask("remove", "tools").stderr, `removed local/team/tools`)
		eq(t, s.ask("hello").code, 2)
	})
	t.Run("every agent, hook and command gets the contract version as ASK_CONTRACT", func(t *testing.T) {
		s := fresh(t)
		s.hook("seen", []string{"task"}, `printf '{"note":"contract %s"}\n' "$ASK_CONTRACT"`)
		r := s.ask("-m", "fake:small", "go")
		eq(t, s.calls()[0].s("contract"), "1")
		match(t, r.stderr, `hook seen · contract 1`)
	})
}
