# frozen_string_literal: true

# Generated by scripts/formula.sh for each release; edit that script, not this file.
class Ask < Formula
  desc "Hand tasks to Claude Code, Codex and Opencode, as subagents"
  homepage "https://fschrhunt.com/ask"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/fschrhunt/ask/releases/download/v0.2.0/ask_v0.2.0_darwin_arm64.tar.gz"
      sha256 "67d182a9e0e3d0f10792b799867fdb1ad82dab7691f980138a77617571d2f907"
    end
    on_intel do
      url "https://github.com/fschrhunt/ask/releases/download/v0.2.0/ask_v0.2.0_darwin_amd64.tar.gz"
      sha256 "9527a9ff1ff5d06c8ca7d32f7ac677006f25428460001571e60da0f722881ae2"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/fschrhunt/ask/releases/download/v0.2.0/ask_v0.2.0_linux_arm64.tar.gz"
      sha256 "f54322466b5807e24f201f4b0c68705311a8bd9570a71179103ed121efaecece"
    end
    on_intel do
      url "https://github.com/fschrhunt/ask/releases/download/v0.2.0/ask_v0.2.0_linux_amd64.tar.gz"
      sha256 "8d8aa0784a802b5440bb0ef4adec36ec8f5e59af700b54a98fba9faddcdc6de4"
    end
  end

  def install
    bin.install "ask"
  end

  def caveats
    <<~EOS
      Next: ask setup
    EOS
  end

  test do
    assert_equal "v0.2.0", shell_output("#{bin}/ask --version").strip
  end
end
