# frozen_string_literal: true

# Generated by scripts/formula.sh for each release; edit that script, not this file.
class Ask < Formula
  desc "Hand tasks to Claude Code, Codex and Opencode, as subagents"
  homepage "https://fschrhunt.com/ask"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/fschrhunt/ask/releases/download/v0.1.0/ask_v0.1.0_darwin_arm64.tar.gz"
      sha256 "ac09104a7643366905c453562a7f1d5bcfb47497b696a1f553dc9433caa833a9"
    end
    on_intel do
      url "https://github.com/fschrhunt/ask/releases/download/v0.1.0/ask_v0.1.0_darwin_amd64.tar.gz"
      sha256 "e15d0ac48709f130c3c2be7da9ecf675407372a11c0f27f7fc0ac05a92f98fdd"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/fschrhunt/ask/releases/download/v0.1.0/ask_v0.1.0_linux_arm64.tar.gz"
      sha256 "03a2798b383fb287e3c4e1797d2bd5822a25c26fb87b0e69cc53e6239c78f89d"
    end
    on_intel do
      url "https://github.com/fschrhunt/ask/releases/download/v0.1.0/ask_v0.1.0_linux_amd64.tar.gz"
      sha256 "aa209106f19be3600914dd7eb7a6b47a0c12ad32da783a834c25d4c66ba651bb"
    end
  end

  def install
    bin.install "ask"
  end

  def caveats
    <<~EOS
      Next: ask setup
    EOS
  end

  test do
    assert_equal "v0.1.0", shell_output("#{bin}/ask --version").strip
  end
end
