/* Only harness differences needed by the offline real-ask tests. */
export const profiles = {
  aider: { model: 'gpt-4o', read: false, session: false, usage: { input: 100, output: 10, cost: 0.01 } },
  amp: { model: 'medium', read: false, usage: { input: 70, output: 14, cached: 40 } },
  claude: { model: 'opus-5.5', usage: { input: 35, output: 7, cached: 20, cost: 0.01 } },
  cline: { model: 'claude-sonnet-5.5', read: false, usage: null, env: { FAKE_TOOLS: 'read_files' }, failure: { FAKE_STOP: 'max_turn_requests' } },
  codex: { model: 'gpt-x', usage: { input: 100, output: 10, cached: 40 } },
  continue: { model: 'model-1.0', cli: 'cn', read: false, session: false, usage: null, answer: 'answer: task', failure: { FAKE_MODE: 'error' } },
  copilot: { model: 'gpt-5.4', usage: { input: 120, output: 5, cached: 40 } },
  cursor: { model: 'gpt-5', cli: 'agent', read: false, usage: null },
  e: { model: 'provider/model', answer: 'answer', usage: { input: 52, output: 10, cached: 6, cost: 0.02 }, failure: { FAKE_ERROR: '1' } },
  gemini: { model: 'gemini-3.5-flash', usage: { input: 120, output: 12, cached: 40 } },
  goose: { model: 'anthropic/claude-sonnet-5-5', read: false, continuationUsage: null, usage: { input: 150, output: 17, cached: 40, cost: 0.003 } },
  kilo: { model: 'zeta/glm-5', usage: { input: 50, output: 7, cached: 10, cost: 0.002 } },
  kimi: { model: 'kimi-for-coding', usage: null },
  opencode: { model: 'm', usage: { input: 50, output: 7, cached: 10, cost: 0.002 } },
  openhands: { model: 'model-1.0', read: false, usage: null, answer: 'final answer', failure: { FAKE_MODE: 'error' } },
  pi: { model: 'provider/model', answer: 'answer parts', usage: { input: 50, output: 10, cached: 6, cost: 0.02 }, failure: { FAKE_REASON: 'error' } },
  qwen: { model: 'qwen-3-coder-plus', read: false, usage: { input: 50, output: 7, cached: 10 } },
  vibe: { model: 'model-1.0', read: false, usage: null, answer: 'final answer', failure: { FAKE_MODE: 'error' } },
};
