#!/bin/sh
# Writes ask.rb, the Homebrew formula that installs a release's binary, from the release's
# checksums.txt. The release workflow runs it after publishing; ask's repository is its own tap:
#
#   brew tap fschrhunt/ask https://github.com/fschrhunt/ask && brew install ask
#
# usage: scripts/formula.sh vX.Y.Z CHECKSUMS > ask.rb
set -eu
tag=$1
sums=$2
sha() { grep " ask_${tag}_$1.tar.gz\$" "$sums" | cut -d' ' -f1; }
url() { echo "https://github.com/fschrhunt/ask/releases/download/$tag/ask_${tag}_$1.tar.gz"; }
for target in darwin_arm64 darwin_amd64 linux_arm64 linux_amd64; do
  [ -n "$(sha "$target")" ] || { echo "formula.sh: no checksum for $target in $sums" >&2; exit 1; }
done
cat <<RUBY
# frozen_string_literal: true

# Generated by scripts/formula.sh for each release; edit that script, not this file.
class Ask < Formula
  desc "Hand tasks to Claude Code, Codex and Opencode, as subagents"
  homepage "https://fschrhunt.com/ask"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "$(url darwin_arm64)"
      sha256 "$(sha darwin_arm64)"
    end
    on_intel do
      url "$(url darwin_amd64)"
      sha256 "$(sha darwin_amd64)"
    end
  end

  on_linux do
    on_arm do
      url "$(url linux_arm64)"
      sha256 "$(sha linux_arm64)"
    end
    on_intel do
      url "$(url linux_amd64)"
      sha256 "$(sha linux_amd64)"
    end
  end

  def install
    bin.install "ask"
  end

  def caveats
    <<~EOS
      Next: ask setup
    EOS
  end

  test do
    assert_equal "$tag", shell_output("#{bin}/ask --version").strip
  end
end
RUBY
